# Generated by Django 2.1.15 on 2020-05-27 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='edit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Form_no', models.CharField(max_length=255)),
                ('Status', models.CharField(max_length=255)),
                ('Applicant_name', models.CharField(max_length=255)),
                ('FAther_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('CNIC', models.CharField(max_length=255)),
                ('Address', models.CharField(max_length=255)),
                ('Hafiz_e_Quran', models.BooleanField()),
                ('District', models.CharField(max_length=255)),
                ('Religion', models.CharField(max_length=255)),
                ('Country', models.CharField(max_length=255)),
                ('Program', models.CharField(max_length=255)),
                ('DOB', models.DateField()),
                ('Gender', models.CharField(max_length=255)),
                ('Martial_Status', models.CharField(max_length=255)),
            ],
        ),
    ]
