# Generated by Django 2.1.15 on 2020-05-27 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edit', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='edit',
            old_name='FAther_name',
            new_name='Father_name',
        ),
    ]
